/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as NfeRouteImport } from './routes/nfe'
import { Route as FluxoDeCaixaRouteImport } from './routes/fluxo-de-caixa'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesUsuariosRouteImport } from './routes/configuracoes.usuarios'
import { Route as ConfiguracoesFiscalRouteImport } from './routes/configuracoes.fiscal'

const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const NfeRoute = NfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoDeCaixaRoute = FluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesUsuariosRoute = ConfiguracoesUsuariosRouteImport.update({
  id: '/configuracoes/usuarios',
  path: '/configuracoes/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesFiscalRoute = ConfiguracoesFiscalRouteImport.update({
  id: '/configuracoes/fiscal',
  path: '/configuracoes/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/nfe': typeof NfeRoute
  '/pdv': typeof PdvRoute
  '/configuracoes/fiscal': typeof ConfiguracoesFiscalRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/nfe': typeof NfeRoute
  '/pdv': typeof PdvRoute
  '/configuracoes/fiscal': typeof ConfiguracoesFiscalRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/nfe': typeof NfeRoute
  '/pdv': typeof PdvRoute
  '/configuracoes/fiscal': typeof ConfiguracoesFiscalRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/estoque'
    | '/fluxo-de-caixa'
    | '/nfe'
    | '/pdv'
    | '/configuracoes/fiscal'
    | '/configuracoes/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/estoque'
    | '/fluxo-de-caixa'
    | '/nfe'
    | '/pdv'
    | '/configuracoes/fiscal'
    | '/configuracoes/usuarios'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/estoque'
    | '/fluxo-de-caixa'
    | '/nfe'
    | '/pdv'
    | '/configuracoes/fiscal'
    | '/configuracoes/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  FluxoDeCaixaRoute: typeof FluxoDeCaixaRoute
  NfeRoute: typeof NfeRoute
  PdvRoute: typeof PdvRoute
  ConfiguracoesFiscalRoute: typeof ConfiguracoesFiscalRoute
  ConfiguracoesUsuariosRoute: typeof ConfiguracoesUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfe': {
      id: '/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof NfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-de-caixa': {
      id: '/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof FluxoDeCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/usuarios': {
      id: '/configuracoes/usuarios'
      path: '/configuracoes/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof ConfiguracoesUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/fiscal': {
      id: '/configuracoes/fiscal'
      path: '/configuracoes/fiscal'
      fullPath: '/configuracoes/fiscal'
      preLoaderRoute: typeof ConfiguracoesFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  FluxoDeCaixaRoute: FluxoDeCaixaRoute,
  NfeRoute: NfeRoute,
  PdvRoute: PdvRoute,
  ConfiguracoesFiscalRoute: ConfiguracoesFiscalRoute,
  ConfiguracoesUsuariosRoute: ConfiguracoesUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
